sudo: required
services:
  - docker

before_install:
  - docker build -t glioympas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true glioympas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-655404144013"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"